config/routes.rb
Rails.application.routes.draw do
  resources :operating_systems
  resources :os
  resources :service_types
  get 'search/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :commands
  resources :services
  resources :types
  resources :domains
  resources :uses

  get 'roles/users'
  post   'roles/role/:id', to: 'roles#add_role', as: 'roles/add_role'
  delete 'roles/role/:id', to: 'roles#remove_role', as: 'roles/remove_role'

  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :servers do
    resources :instances
  end
  get 'servers/:server_id/instances/:id/check/:command_id', to: 'instances#check', as: 'instances/check'
  get 'instances/search_service/:service_id', to: 'instances#search_service', as: 'instances/search_service'
  get 'instances/reload_service/:service_id', to: 'instances#reload_service', as: 'instances/reload_service'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instance.rb
class Instance < ApplicationRecord
  resourcify
  belongs_to :server, :foreign_key => "server_id"
  belongs_to :service
  belongs_to :service_type
  validates_presence_of :name, :port
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  protect_from_forgery with: :null_session, if: ->{request.format.json?}
  before_action :authenticate_user!
  before_action :set_instance, only: [:show, :edit, :update, :destroy, :check]

  # GET servers/1/instances
  # GET servers/1/instances.json
  def index
    @user = User.new
    @title = t('actions.listing') + " " + t('activerecord.models.instances')
    @edit   = helpers.set_edit(current_user)
    @manage = helpers.set_manage(current_user)
    # legge server
    @server = Server.find(params[:server_id])
    @commands = Command.all

    # paginazione
    # default 10 righe per pagina
    if params[:per_page].nil? || params[:per_page].to_s.strip.length == 0
      params[:per_page] = 5
    end
    # ricerca
    @instances = @server.instances.page(params[:page]).per(params[:per_page])

  end

  # GET servers/1/instances/1
  # GET servers/1/instances/1.json
  def show
  end

  # GET servers/1/instances/new
  def new
    @title = t('actions.new') + " " + t('activerecord.models.instance')
    @server = Server.find(params[:server_id])
    @instance = Instance.new
    @service = Service.new
    @url = server_instances_path
  end

  # GET servers/1/instances/1/edit
  def edit
    @title = t('actions.edit') + " " + t('activerecord.models.instance')
    @server = Server.find(params[:server_id])
    @url = server_instance_path
    @service = Service.find(@instance.service_id)
  end

  # POST servers/1/instances
  # POST servers/1/instances.json
  def create
    @title = t('actions.new') + " " + t('activerecord.models.instance')
    @instance = Instance.new(instance_params)
    @server = Server.find(params[:server_id])
    @instance.server_id = params[:server_id]
    @service = Service.find(@instance.service_id)
    @url = server_instances_path

    respond_to do |format|
      if @instance.save
        format.html { redirect_to server_instances_path, notice: t('activerecord.models.instance') + " " + t('notice.create') }
        format.json { render :index, status: :created, location: @instance }
      else
        format.html { render :new }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT servers/1/instances/1
  # PATCH/PUT servers/1/instances/1.json
  def update
    @title = t('actions.edit') + " " + t('activerecord.models.instance')
    @url = server_instance_path
    @server = Server.find(params[:server_id])

    respond_to do |format|
      if @instance.update(instance_params)
        format.html { redirect_to server_instances_path, notice: t('activerecord.models.instance') + " " + t('notice.update') }
        format.json { render :index, status: :ok, location: @instance }
      else
        format.html { render :edit }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /server/1/istances/destroy
  # DELETE /server/1/istances/destroy.json
  def destroy
    @server = Server.find(params[:server_id])
    @server.instances.delete(params[:id])
    respond_to do |format|
      format.html { redirect_to server_instances_path, notice: t('activerecord.models.instance') + " " + t('notice.delete') }
      format.json { head :no_content }
    end
  end

  # GET servers/1/instances/1/check/1
  # GET servers/1/instances/1/check/1.json
  def check
    @command = Command.find(params[:command_id])
    @server = Server.find(params[:server_id])
    #    @result = %x[#{@command.exec}; echo "#{@instance.name}/#{@instance.port}"]

    if @command.query.blank?
      @result = %x[#{@command.exec}]
    else
      @result = %x[#{@command.query}]
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET instances/search_service/1
  # GET instances/search_service/1.json
  def search_service
    @service = Service.find(params[:service_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET instances/reload_service/1
  # GET instances/reload_service/1.json
  def reload_service
    @service = Service.find(params[:service_id])
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instance
      @instance = Instance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instance_params
      params.require(:instance).permit(:server_id, :name, :port, :service_id, :service_type_id, :note, :check, :command_id)
    end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_check.html.erb
<%= @result %>

app/views/instances/_form.html.erb
<div class="container-fluid form_web col-md-offset-1 col-md-10">
<%= simple_form_for @instance, :url => @url do |f| %>
  <% if @instance.errors.any? %>
    <div class="alert alert-danger">
  	  <a class="close" data-dismiss="alert">&#215;</a>
      <div><b> <%= t('actions.attention') %>
        <%= pluralize(@instance.errors.count, t('activerecord.errors.messages.error'), t('activerecord.errors.messages.errors')) %>:</b>
      </div>
      <ul>
        <% @instance.errors.full_messages.each do |msg| %>
          <li class="fatal_error"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row col-md-12">
    <fieldset>
      <legend>Server:</legend>
      <div class="col-md-3">
        <%= f.input :server_id, as: :hidden %>
        <b><%= @server.ip %></b>
      </div>
      <div class="col-md-9">
        <b><%= @server.name %></b>
      </div>
    </fieldset>
    </br></br>
    <fieldset>
      <legend>Servizio:</legend>
      <div class="col-md-3">
        <%= f.input :name, input_html: { size: 10 } %>
      </div>
      <div class="col-md-2">
        <%= f.input :port, input_html: { size: 10, readonly: @change } %>
      </div>
      <div class="col-md-4">
        <div class="pull-left">
          <%= f.label :service %>
          <div class="input-group">
            <%= f.association :service, label_method: :description, label: false, input_html: {class: "pull-left form-control"} %>
            <script>
              $("#instance_service_id").change(function() {
                $.ajax({
                    type: 'GET',
                    url: '../../../../instances/reload_service/'+$('#instance_service_id').val()
                });
              })
            </script>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <%= f.association :service_type, label_method: :code %>
      </div>
      <% unless @service.nil? %>
      <div class="col-md-12">
        <table class="table table-striped table-condensed table-hover">
          <tr>
            <th> <%= t('activerecord.attributes.service.department') %> </th>
            <th> <%= t('activerecord.attributes.service.area') %> </th>
            <th> <%= t('activerecord.attributes.service.referent') %> </th>
            <th> <%= t('activerecord.attributes.service.state') %> </th>
          </tr>
          <tr>
            <td id="td1"><%= @service.department %></td>
            <td id="td2"><%= @service.area %></td>
            <td id="td3"><%= @service.referent %></td>
            <td id="td4"><%= @service.state %></td>
          </tr>
        </table>
      </div>
      <% end %>
    </fieldset>
    <fieldset>
      <legend>Note:</legend>
      <div class="col-md-12">
        <%= f.input :note, input_html: { cols: 150, rows: 10, readonly: @change } %>
      </div>
    </fieldset>
    <fieldset>
      <legend>Controllo:</legend>
      <div class="col-md-12">
        <div><%= f.label :check %></div>
        <%= f.input_field :check, as: :boolean %>
      </div>
    </fieldset>
    </br></br>
    <div class="col-md-12">
      <%= link_to server_instances_path, :class => "btn btn-default btn-lg", :title => t('actions.back'), :alt => t('actions.back') do %>
        <span class="glyphicon glyphicon-arrow-left"></span> <%= t('actions.back') %>
      <% end %>
      <%= button_tag(type: 'submit', class: "btn btn-primary btn-lg") do %>
        <span class="glyphicon glyphicon-ok glyphicon-inverse"></span> <%= t('actions.update') %>
      <% end %>
      </br></br>
    </div>
  </div>
<% end %>
</div>

app/views/instances/_header.html.erb
<div class="col-md-12">
  <div class="col-md-3">
    <!--%= render 'search_server' %-->
  </div>
  <div class="col-md-2">
    <%= render 'per_page_instance' %>
  </div>
  <div class="col-md-offset-1">
    <%= unless @instances.nil?; paginate @instances; end %>
  </div>
</div>

app/views/instances/_header_sub.html.erb
<div class="container-fluid">
<ol class="breadcrumb col-md-6">
  <li><%= link_to Server, servers_path %></li>
  <li><%= link_to "Istanza", server_instances_path %></li>
  <li class="active"><%= title %></li>
</ol>
</div>

app/views/instances/_per_page_instance.html.erb
<div class="pull-left">
<%= form_tag server_instances_path, :method => 'get', :class => "form-group pull-right form-inline", :role => "form" do %>
  <div class="input-group">
    <%= number_field_tag :per_page, params[:per_page], :class => "pull-left form-control", :type => "number", :min => 1 %>
    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span></button>
    </span>
  </div>
<% end %>
</div>

app/views/instances/_search_service.html.erb
<div id="search_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="_search_service" aria-hidden="true">
<%= simple_form_for @service, :url => instances_search_service_path(@service) do |f| %>
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class='modal-header'>
      <button type="button" class="close" data-dismiss="modal" aria-label="Chiudi"><span aria-hidden="true">&times;</span></button>
      <h3 class="modal-title">Ricerca Servizio</h3>
    </div>
    <div class='modal-body'>
      <div class="modal-body-content">
        <div class="form-group">
          <%= f.input :description, input_html: { size: 30 } %>
        </div>
      </div>
    </div>
    <br />
    <div class='modal-footer'>
      <div class="form-group">
        <%= link_to instances_search_service_path(@service), :class => "btn btn-primary" do %>
          <span class="glyphicon glyphicon-ok glyphicon-inverse"></span> Cerca
        <% end %>
        <button type="button" data-dismiss="modal" class="btn btn-default">
          <span class="glyphicon glyphicon-arrow-left"></span> Chiudi
        </button>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/instances/check.html.erb
<%= render 'header_sub1' %>
<div class="col-md-12">
<%= render 'header' %>
<br /><br />
  <%= @result %>
</div>

app/views/instances/check.js.erb
$("#result<%= @instance.id %>").html("<%= @result.to_json %>");

app/views/instances/edit.html.erb
<%= render 'header_sub' %>
<%= render 'form', instance: @instance %>

app/views/instances/index.html.erb
<%= render 'header_sub1' %>
<div class="col-md-12">
<%= render 'header' %>
<br /><br />
<div class="panel-group" id="accordion" role="tablist">
<div class="panel panel-default">
  <a class="accordion-toggle" tabindex="0" data-toggle="collapse" data-parent="#accordion" href="#server" aria-controls="server">
    <div class="panel-heading panel-heading-dark" role="tab">
	  <div class="panel-title">
	  	&nbsp&nbsp <%= t('activerecord.attributes.server.ip') %>: <strong><%= @server.ip %></strong>
	    &nbsp&nbsp <%= t('activerecord.attributes.server.name') %>: <strong><%= @server.name %></strong>
  	  &nbsp&nbsp <%= t('activerecord.attributes.server.use') %>: <strong><%= unless @server.use.nil?; @server.use.description; end %></strong>
      &nbsp&nbsp <%= t('activerecord.attributes.server.type') %>: <strong><%= unless @server.type.nil?; @server.type.description; end %></strong>
      &nbsp&nbsp <%= t('activerecord.attributes.server.operating_system') %>: <strong><%= unless @server.operating_system.nil?; @server.operating_system.description; end %></strong>
	    &nbsp&nbsp <%= t('activerecord.attributes.server.domain') %>: <strong><%= unless @server.domain.nil?; @server.domain.description; end %></strong>
	    <span id="img-panel" class="glyphicon glyphicon-plus pull-right"></span>
	  </div>
    </div>
  </a>
  <div id="server" class="panel-collapse collapse" role="tabpanel">
	<div class="panel-body" tabindex="0">
	  <div class="table-responsive">
        <table class="table table-hover table-condensed">
          <thead>
            <tr>
              <th><%= t('activerecord.attributes.server.description') %></th>
              <th><%= t('activerecord.attributes.server.note') %></th>
              <th><%= t('activerecord.attributes.server.manage') %></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @server.description %></td>
              <td><%= @server.note %></td>
              <td><% if @server.manage %>
                    <span class="label label-success">Sì</span>
                  <% else %>
                    <span class="label label-danger">No</span>
                  <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

<table class="table table-striped table-condensed table-hover">
  <thead>
  <tr>
    <th class="panel-lispa"><%= t('activerecord.attributes.instance.service') %></th>
    <th class="panel-lispa"><%= t('activerecord.attributes.instance.name') %></th>
    <th class="panel-lispa"><%= t('activerecord.attributes.instance.port') %></th>
    <th class="panel-lispa"><%= t('activerecord.attributes.instance.note') %></th>
    <th class="panel-lispa"><%= t('activerecord.attributes.instance.check') %></th>
    <th class="panel-lispa" colspan=4><%= t('actions.actions') %></th>
  </tr>
  </thead>
  <tbody>
    <% @instances.each do |instance| %>
      <tr>
        <td><%= unless instance.service.nil?; link_to instance.service.description, instance.service.card; end %></td>
        <td><%= instance.name %></td>
        <td><%= instance.port %></td>
        <td><%= instance.note %></td>
        <td>
          <% if instance.check %>
            <span class="label label-success">Sì</span>
          <% else %>
            <span class="label label-danger">No</span>
          <% end %>
        </td>
        <td>
          <% if @edit then @class = "btn btn-primary" else @class = "btn btn-primary disabled" end %>
          <%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>'),
          edit_server_instance_path(instance.server_id, instance), class: @class, title: t('actions.edit'), alt: t('actions.edit'), data: {toggle: "tooltip", placement: "left" } %>
        </td>
        <td>
          <% if @manage then @class = "btn btn-default" else @class = "btn btn-default disabled" end %>
          <%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'),
          server_instance_path(instance.server_id, instance), method: :delete, data: { confirm: t('actions.are_you_sure'), toggle: "tooltip", placement: "left" },
          class: @class, title: t('actions.destroy'), alt: t('actions.destroy') %>
        </td>
        <td>
          <% if @edit then @class = "btn btn-primary" else @class = "btn btn-primary disabled" end %>
          <a class="<%= @class %> glyphicon glyphicon-check" role="button" data-toggle="collapse" href="#collapseArea<%= instance.id %>"
            aria-expanded="false" aria-controls="collapseArea<%= instance.id %>" title="<%= t('actions.check') %>" alt="<%= t('actions.check') %>">
          </a>
        </td>
      </tr>
      <tr>
        <td>
          <div class="collapse well-command" id="collapseArea<%= instance.id %>">
            <table class="table-striped table-condensed table-hover">
              <tbody>
                <tr>
                <% @commands.each do |command| %>
                  <td>
                    <% if command.unix and @server.operating_system.unix %>
                    <%= link_to command.code, instances_check_path(instance.server_id, instance, command.id),
                        class: @class, role: "button", title: command.description, alt:command.description,
                        remote: true %>
                    <% else %>
                    <% if command.win and @server.operating_system.win %>
                    <%= link_to command.code, instances_check_path(instance.server_id, instance, command.id),
                        class: @class, role: "button", title: command.description, alt:command.description,
                        remote: true %>
                    <% end %>
                    <% end %>
                  </td>
                <% end %>
                </tr>
                <tr>
                  <td colspan="12" class="well-command" id="result<%= instance.id %>"></td>
                </tr>
              </tbody>
            </table>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<% if @manage then @class = "btn btn-round red" else @class = "btn btn-round red disabled" end %>
<%= link_to new_server_instance_path(@server.id), class: @class, title: t('actions.new'), alt: t('actions.new') do %>
  <span class="glyphicon glyphicon-plus"></span>
<% end %>

app/views/instances/new.html.erb
<%= render 'header_sub' %>
<%= render 'form', instance: @instance %>

app/views/instances/reload_service.js.erb
$("#td1").html("<%= @service.department %>");
$("#td2").html("<%= @service.area %>");
$("#td3").html("<%= @service.referent %>");
$("#td4").html("<%= @service.state %>");

app/views/instances/search_service.html.erb
<%= render 'instances/search_service' %>

app/views/instances/search_service.js.erb
$("#search_modal").html("<%= escape_javascript(render 'instances/search_service') %>");