config/routes.rb
Rails.application.routes.draw do
  resources :operating_systems
  resources :os
  resources :service_types
  get 'search/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :commands
  resources :services
  resources :types
  resources :domains
  resources :uses

  get 'roles/users'
  post   'roles/role/:id', to: 'roles#add_role', as: 'roles/add_role'
  delete 'roles/role/:id', to: 'roles#remove_role', as: 'roles/remove_role'

  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :servers do
    resources :instances
  end
  get 'servers/:server_id/instances/:id/check/:command_id', to: 'instances#check', as: 'instances/check'
  get 'instances/search_service/:service_id', to: 'instances#search_service', as: 'instances/search_service'
  get 'instances/reload_service/:service_id', to: 'instances#reload_service', as: 'instances/reload_service'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :user
      can :read, :all
      can :update, :all
    elsif user.has_role? :reader
      can :read, :all
    else
      can :read, Server
      can :read, Instance
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/command.rb
class Command < ApplicationRecord
end

app/models/domain.rb
class Domain < ApplicationRecord
  has_many :server
end

app/models/instance.rb
class Instance < ApplicationRecord
  resourcify
  belongs_to :server, :foreign_key => "server_id"
  belongs_to :service
  belongs_to :service_type
  validates_presence_of :name, :port
end

app/models/operating_system.rb
class OperatingSystem < ApplicationRecord
  has_many :server
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/server.rb
class Server < ApplicationRecord
  resourcify
  has_many :instances, dependent: :destroy
  validates_presence_of :ip, :name, :use_id, :domain_id
  validates :ip, uniqueness: true
  validate :ip_valid
  belongs_to :use
  belongs_to :domain
  belongs_to :type
  belongs_to :operating_system

  def ip_valid
    begin
      IPAddr.new(ip)
    rescue IPAddr::InvalidAddressError
      errors.add(:ip, "formato invalido: #{ip}")
    end
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :instance
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
  has_many :instance
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :server
end

app/models/use.rb
class Use < ApplicationRecord
  has_many :server
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, password_length: 6..25

  validate  :email_domain

  def email_domain
    if !WEBDEV['users_email_domain_validation_regex'].nil?
      r = Regexp.new(WEBDEV['users_email_domain_validation_regex'])
      if (r =~ email).nil?
        errors.add(:email, :invalid_domain)
      end
    end
  end

end

app/controllers/operating_systems_controller.rb
class OperatingSystemsController < InheritedResources::Base

  private

    def operating_system_params
      params.require(:operating_system).permit(:code, :description, :unix, :win)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/operating_systems_helper.rb
module OperatingSystemsHelper
end

app/helpers/os_helper.rb
module OsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/uses_helper.rb
module UsesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/operating_systems/_form.html.erb
<%= simple_form_for(@operating_system) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/operating_systems/edit.html.erb
<h1>Editing Operating System</h1>

<%= render 'form', operating_system: @operating_system %>

<%= link_to 'Show', @operating_system %> |
<%= link_to 'Back', operating_systems_path %>

app/views/operating_systems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Operating Systems</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operating_systems.each do |operating_system| %>
      <tr>
        <td><%= operating_system.code %></td>
        <td><%= operating_system.description %></td>
        <td><%= link_to 'Show', operating_system %></td>
        <td><%= link_to 'Edit', edit_operating_system_path(operating_system) %></td>
        <td><%= link_to 'Destroy', operating_system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operating System', new_operating_system_path %>

app/views/operating_systems/new.html.erb
<h1>New Operating System</h1>

<%= render 'form', operating_system: @operating_system %>

<%= link_to 'Back', operating_systems_path %>

app/views/operating_systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @operating_system.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @operating_system.description %>
</p>

<%= link_to 'Edit', edit_operating_system_path(@operating_system) %> |
<%= link_to 'Back', operating_systems_path %>